### ISSUE TITLE
Cassandra 3.x support

### ISSUE THREAD

**Issue by klinux** [pentaho/pentaho-cassandra-plugin#68]
Is there plans to support cassandra 3.x series?

Thank you

**Comment by k3nnyP** [comment]
bump.  Are there any plans for Cassandra 3.x support?

**Comment by matthewtckr** [comment]
Hi @k3nnyP and @klinux, we track improvements via our JIRA system, instead of GitHub issues.  Take a look at http://jira.pentaho.com/browse/PDI-15116.

**Comment by k3nnyP** [comment]
Thanks.
